### ISSUE TITLE
NodeJS required for listing ejectable drives

### ISSUE THREAD

**Issue by Rundfunk** [fabiospampinato/alfred-eject-workflow#1]
Hi @fabiospampinato,

Thank you for making this useful workflow!

I tried installing it, but couldn't get it to work straight away: after typing `eject `, a list of drives didn't appear. After looking at the workflow, I noticed that a NodeJS script is used to generate this list.

Can you list NodeJS as a dependency in the readme, for other people running into the same problem?

**Comment by fabiospampinato** [comment]
Done, thanks for the suggestion.
